### ISSUE TITLE
Not working in Ember 4 with ember-test-selectors v5 (bump to 6 needed)

### ISSUE THREAD

**Issue by pjcarly** [adopted-ember-addons/ember-sortable#463] opened 2022-01-29 00:09 UTC
Upgraded our app to Ember 4, and having issues with the build. Narrowed it down to this addon. When this addon is installed I get the below errors in browser console.
Not there when the addon is not installed.

```
patch-component.js:6 Uncaught ReferenceError: Ember is not defined
    at patch-component.js:6:1
    at patch-component.js:15:1
(anonymous) @ patch-component.js:6
(anonymous) @ patch-component.js:15

loader.js:247 Uncaught Error: Could not find module `ember-resolver` imported from `<snip>/app`
    at missingModule (loader.js:247:1)
    at findModule (loader.js:258:1)
    at Module.findDeps (loader.js:168:1)
    at findModule (loader.js:262:1)
    at requireModule (loader.js:24:1)
    at app-boot.js:3:1
```

**Comment by Turbo87** [comment] 2022-01-29 04:17
@pjcarly can you provide a reproduction? seems to work fine here 🤔

**Comment by BobrImperator** [comment] 2022-01-29 05:44
Is it possible that `ember-test-selectors` are also a dependency of a different package? The latest version of `ember-test-selectors` removed component patching in `v6.0.0`.

https://github.com/simplabs/ember-test-selectors/commit/63f7e49af92feac729b9a572bf1f81180f7adc0c#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346

**Comment by pjcarly** [comment] 2022-02-02 12:51
only `ember-sortable` has a dependency on `ember-test-selectors` according to my yarn.lock file @BobrImperator 

Resolved version is `version "5.5.0"`

**Comment by BobrImperator** [comment] 2022-02-02 13:41
Seems like that's the issue, latest `ember-test-selectors` should work for you.

It also seems like ember-sortable didn't release a new version since specifying `ember-test-selectors` v6.
You can wait for `ember-sortable` to release a new version with bumped `ember-test-selectors` or add a resolution inside your package.json if you're using `yarn` not sure if npm supports resolutions natively.

**Comment by pjcarly** [comment] 2022-02-02 15:19
Resolutions fixed the issue, thanks @BobrImperator. Hope to see a new release soon. (updated the issue title)

**Comment by MelSumner** [comment] 2022-02-07 01:00
Ok since it's determined that a new release will resolve the issue, I'm closing this in favor of #457

**Closed by MelSumner** 2022-02-07 01:00 UTC
