### ISSUE TITLE
'onChange' not getting triggered after version 1.12.4 update

### ISSUE THREAD

**Issue by RVenkatesh** [adopted-ember-addons/ember-sortable#234] opened 2019-02-16 09:31 UTC
We had been using the sortable for few months. After the 1.12.4 update, the 'onChange' event is not getting triggered. I am testing using Chrome 71.0.3578.98 (Official Build) (64-bit). Below is the code sample.

```
{{#sortable-group onChange=(action "reorderOptions") as |group|}}
	{{#each (sort-by "sortorder" options) as |option|}}
		{{#sortable-item model=option group=group class="option" handle=".sort-handle"}}
			{{#if (and canEdit (gt options.length 1))}}
				<i class="fa fa-bars sort-handle"></i>
			{{/if}}
			{{option-comp}}
		{{/sortable-item}}
	{{/each}}
{{/sortable-group}} 
```

And the component js file has the action
```
reorderOptions(options, movedOption) {
     // Commit to model code
}
```

I have not added the full code for the action, since the action itself is not getting called anyway. I did some digging and looks like the `commit` function itself is not getting called inside the addon. 

Any help would be great. Thank you in advance.

**Comment by dhinesh03** [comment] 2019-02-16 10:42
I too have this issue.

**Comment by jgwhite** [comment] 2019-02-18 06:23
Thanks for reporting. It seems like the changes we introduced to fix some Firefox issues have caused regressions elsewhere. Will report back when we have a plan to move ahead. As a temporary measure, we recommend pinning to 1.12.3.

**Comment by BnitoBzh** [comment] 2019-06-04 09:09
YES !!! I found a (the?) solution !!! 🎉 
All `.sortable-item` MUST have a css property with a transition like `transition: all .125s;`
Because, if not, the event `transistionend` is not fired in Firefox. (due to the `_waitForTransition` function refactor on the "sortable-item" Mixin that adds this behavior)

Sass/CSS example to fix the issue : 
```css
// in scss or sass file
.sortable-item {
  transition: all .125s;
  
  &.is-dragging {
    transition-duration: 0s;
  }
}

// or in css file
.sortable-item {
  transition: all .125s;
}
.sortable-item.is-dragging {
  transition-duration: 0s;
}
```

**Comment by jgwhite** [comment] 2019-06-04 10:35
@BnitoBzh good catch. Do you think there’s anything you could add to the core core to ensure these conditions are met?

**Comment by BnitoBzh** [comment] 2019-06-04 10:47
I think there is nothing to add to the core code, a simple README update can be made to explain the CSS requirement for Firefox. (a simple note like my previous comment after the installation instructions)

**Comment by xtagon** [comment] 2019-06-04 16:44
Note that this is affecting Chrome (according to the issue owner, and I also saw the issue in Chrome) and possibly other browsers, not just Firefox.

**Comment by RVenkatesh** [comment] 2019-06-04 16:53
> Note that this is affecting Chrome (according to the issue owner, and I also saw the issue in Chrome) and possibly other browsers, not just Firefox.

Rightly said. I saw the issue occur in Chrome. Not sure about Firefox though.

**Comment by jgwhite** [comment] 2019-06-04 22:46
To me it sounds like we need to fix `_waitForTransition` and the `isAnimated` property to do a better job of detecting animation conditions. If you have an idea how to fix it, please don’t hesitate to open a PR.

A PR that adds workaround details to the README would be a welcome interim measure.

**Comment by AdminDev826** [comment] 2019-06-18 02:52
I've updated version to `^1.12.9` and added the following styles.
Now `onChange` event works well. :)
Thank you. @BnitoBzh
Sass/CSS example to fix the issue :

// in scss or sass file
.sortable-item {
  transition: all .125s;
  
  &.is-dragging {
    transition-duration: 0s;
  }
}

// or in css file
.sortable-item {
  transition: all .125s;
}
.sortable-item.is-dragging {
  transition-duration: 0s;
}

**Comment by mdbiscan** [comment] 2019-09-03 18:11
I'm seeing an issue here as well. Adding the CSS fixes a bug in Firefox, where the last moved item loses its draggability without displaying errors. However, the onChange event still never fires. I'm on FireFox 68.0.2 for Ubuntu.

**Comment by sharpshark28** [comment] 2019-12-21 20:45
Thanks for this css fix, I ran into this on Firefox just today.

**Comment by ygongdev** [comment] 2021-01-08 19:50
I'm going to close this ticket as we no longer support version `1.x` and the above solution is a good animated fix.

**Closed by ygongdev** 2021-01-08 19:50 UTC
