### ISSUE TITLE
Keyboard drag/drop doesn't move differently sized items correctly

### ISSUE THREAD

**Issue by michaeldrotar** [adopted-ember-addons/ember-sortable#307] opened 2019-11-04 17:49 UTC
**Describe the bug**
When using differently-sized items, mouse-drag works as expected, but keyboard drag can overlap items rather than moving them into the empty spaces.

**To Reproduce**
1. Go to demo page: https://adopted-ember-addons.github.io/ember-sortable/demo/
2. Use dev tools to add more text to one of the items so that it's bigger (might be nice to officially update a demo to show differently sized items)
3. Tab to an item, hit enter to start keyboard mode, use arrow keys to move a smaller item beneath a larger item
4. See that the item overlaps the bigger item, and other items that move to the dragging item's former position likewise overlap

**Expected behavior**
Item should move into the empty spaces created

**Screenshots**
![image](https://user-images.githubusercontent.com/820263/68142544-a16d8100-fefd-11e9-8c9a-fea4cffdc90b.png)
In this screenshot, the Tres item was second in the list and I'm using the keyboard mode to move it down, have not yet dropped it.

![image](https://user-images.githubusercontent.com/820263/68145169-2eff9f80-ff03-11e9-91ce-0be0fbefe2f6.png)
In this screenshot, the bigger item was in the third spot and I moved it down to the fourth but it overshot its destination and is overlapping the fifth item. If I move it down again, it overshoots again and rests outside of the container.

**Additional context**
Great lib! Mouse and keyboard both work exactly how I wanted so going to save me time over building something, hope this minor bug isn't too painful :D

**Comment by ygongdev** [comment] 2019-11-04 18:01
Thanks for the report, are you able to reproduce this everytime when you re-order? I wasn't able to reproduce it :(

I think there might sometimes be a race condition in the reorder flow, so if you're able to consistently to reproduce it, let me know because it would make it easier for me to debug and fix long-term

**Comment by michaeldrotar** [comment] 2019-11-04 20:22
@ygongdev hm yup everytime using both mac and windows, latest chrome, even tried refreshing the browser in case the race condition was during load. It's perfectly consistent for me when using the keyboard.

Here's a fresh refresh.. I added text to Dos and am in the process of moving Uno to the bottom.

![image](https://user-images.githubusercontent.com/820263/68154949-b571ac80-ff16-11e9-8f15-6719ea780c59.png)

**Comment by ygongdev** [comment] 2019-11-04 21:18
@michaeldrotar Ah I see thanks! I know what's wrong now. Need to re-visit how to recompute the positions when using keyboard.

**Comment by ygongdev** [comment] 2019-11-09 06:20
@michaeldrotar try upgrading to `2.0.2` this should be fixed. I'll update the demo with an example as well.

**Comment by michaeldrotar** [comment] 2019-11-09 20:49
@ygongdev I can confirm 2.0.2 is working for me locally now, great job!

**Closed** 2019-11-09 21:00 UTC
Labels: bug, v2
