### ISSUE TITLE
Uncaught TypeError after 2.0.1 upgrade

### ISSUE THREAD

**Issue by gtb104** [adopted-ember-addons/ember-sortable#306] opened 2019-11-04 14:09 UTC
**Describe the bug**
Getting Uncaught TypeError after upgrading to 2.0.1.

**To Reproduce**
1. Going to a page that has an ember-sortable component causes an Uncaught TypeError, and the page fails to load.

**Expected behavior**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/1440968/68126294-7c6b1500-fee1-11e9-972b-8e77b0707e4b.png)

**Additional context**
This is my template. Please advise if I've done something incorrectly. Just a FYI, `filteredColumns` could be an empty array.
```hbs
      {{#sortable-group tagName='ul' model=filteredColumns class='column-list value editable' onChange=(action 'reorderColumns') as |group|}}
        {{#each group.model as |column|}}
          {{#group.item class='editable' model=column as |columnItem|}}
            {{#form-button class='remove-meta-key' defaultAction=(action 'removeFromColumns' column)}}
              {{x-icon name='subtract-circle-1'}}
            {{/form-button}}
            <span class='field'>{{column.field}}</span>
            <span title={{column.title}} class='title'>{{column.title}}</span>
            {{#columnItem.handle class='thumb'}}
              {{x-icon name='navigation-drawer-1'}}
            {{/columnItem.handle}}
          {{/group.item}}
        {{/each}}
      {{/sortable-group}}
```

I'm able to bypass the error if I modify sortable-item's _tellGroup function like so:
```js
  _tellGroup(method, ...args) {
    let group = this.get('group');

    if (group && group[method]) { // <-- add additional check
      group[method](...args);
    }
  },
```

**Comment by gtb104** [comment] 2019-11-04 14:25
I forgot to mention, the `method` it can't find is `registerItem`.
![image](https://user-images.githubusercontent.com/1440968/68128084-0ec0e800-fee5-11e9-9a31-d87addc53350.png)

**Comment by ygongdev** [comment] 2019-11-04 15:55
Sounds like this is failing for you on the initial load? That seems very odd as registerItem is definitely a method on the sortable-group

**Comment by BnitoBzh** [comment] 2019-11-04 17:19
Fails for me too, same issue. Ember 3.13.x
_This v2.x seems to be be very unstable_

**Comment by BnitoBzh** [comment] 2019-11-04 17:24
Why not pass group's methods directly in the yield definition ?
With this behavior all `group=group` can be removed (from `sortable-item` calls)

**Comment by BnitoBzh** [comment] 2019-11-04 17:36
Ignore my previous comment, the README file is not up-to-date. It could be fixed...

I think the `_tellGroup` method must be like this : 

```javascript
  _tellGroup(method, ...args) {
    let group = this.get('group');

    if (group && 'function' === typeof group[method]) {
      group[method](...args);
    }
  }
```

**Comment by ygongdev** [comment] 2019-11-04 17:42
@BnitoBzh Good catch on the `README.md`. I'll fix that up.
I'll try to take a look today at why this might fail. Because the `demo` seems to be working perfectly fine. If this is an actual issue, I need to understand the root cause and add some test cases to cover it.

**Comment by ygongdev** [comment] 2019-11-05 17:18
If anyone can reproduce this via a twiddle, it would help me tremendously to drill down the issue.

**Comment by ygongdev** [comment] 2019-11-18 22:40
FYI, I've seen a similar error, if the action you provide is a string. This fails due to the removal of `sendAction`,e.g
Bad
`onChange="onChange"`
Good
`onChange=(action "onChange")`

**Comment by mattgraham1995** [comment] 2019-11-21 21:18
@ygongdev I've managed to reproduce the issue that I'm facing in a twiddle. It looks like `_tellGroup` is getting called with `"registerItem"` as the method parameter on initial load of the page. This is the same issue that my tests fail with so I think it is the same.

Take a look here: https://ember-twiddle.com/13854f9271896ef40f49aba938abb496?openFiles=templates.components.my-component.hbs%2Ctemplates.components.other-component.hbs

**Comment by ygongdev** [comment] 2019-11-21 22:48
@mattgraham1995 Thank you for the twiddle! I'll try to root cause this.

**Comment by ygongdev** [comment] 2019-11-22 06:01
@mattgraham1995 @gtb104 @BnitoBzh 
Please try `2.1.0-beta.0`. I believe the issue should be resolved now.
I was able to confirm with this twiddle
https://ember-twiddle.com/ced74cdf949e8f09b43ecc47d258c3ea?openFiles=twiddle.json%2Ctemplates.components.other-component.hbs

**Comment by mattgraham1995** [comment] 2019-11-22 19:52
@ygongdev Thanks for addressing this Jerry. I can confirm that `2.1.0-beta.0` fixes the issue mentioned here. I'm running into another issue now where `_update` in the `sortable-group` component is failing an assert on `set` because it is trying to set on an item that is in the process of destroying. Problem line is here: https://github.com/adopted-ember-addons/ember-sortable/blob/master/addon/components/sortable-group.js#L349

I tried reproducing in a twiddle, but I'm having trouble. I suspect it may be because Ember Twiddle doesn't seem to support anything past Ember 3.4.x but my addon is on 3.12.0

**Comment by ygongdev** [comment] 2019-11-22 19:59
@mattgraham1995 can you link the twiddle where it's suppose to fail?
It could be an issue of a component being destroyed while we're still performing the `update`. 
Can you describes the steps you took to produce it? Thanks!

**Comment by ygongdev** [comment] 2019-11-22 20:05
Or it could be a separate issue depending on what your addon is doing, for example, removing an item from the group etc.

**Comment by mattgraham1995** [comment] 2019-11-22 20:08
I'm still trying to reproduce it in a twiddle, but in my addon the error occurs after dragging an item to reorder. There's no removal or anything happening so I'm not sure why the items are being marked for destruction.

**Comment by ygongdev** [comment] 2019-11-22 20:29
Mind sharing the structure of your addon and how you're invoking everything?

**Comment by mattgraham1995** [comment] 2019-11-22 23:54
@ygongdev Okay I've solved my issue. As I suspected, it was a problem with the way my dummy app was mocking some actions. Thanks for the quick fix with this issue!

**Comment by ygongdev** [comment] 2019-11-23 00:02
@mattgraham1995 awesome! I'll close this issue for now then and cut an official release

**Closed** 2019-11-23 00:03 UTC
Labels: bug, help wanted, v2

**Comment by gtb104** [comment] 2020-01-08 18:24
Sorry, just had a chance to look at this. I'm seeing a different, but similar issue now that I'm on the latest (2.1.1). The below errors are seen on page load.
![Screen Shot 2020-01-06 at 2 47 01 PM](https://user-images.githubusercontent.com/1440968/72004436-6c412000-3219-11ea-9d78-72df2373877f.png)
The HBS is the same as above.

**Comment by gtb104** [comment] 2020-01-08 18:37
![image](https://user-images.githubusercontent.com/1440968/72005588-f12d3900-321b-11ea-8926-246474b6893a.png)

**Comment by ygongdev** [comment] 2020-01-09 19:56
@gtb104 can you list the steps to reproduce your error?
I'm guessing this isn't from the initial load of the component, but rather after some sort of operation ,e.g after a reorder.

**Comment by ygongdev** [comment] 2020-01-09 19:57
Might be worthwhile to move this discussions to a new ticket, as it is a different error from this closed ticket.

**Comment by gtb104** [comment] 2020-01-13 13:25
I'll try to gather some more info on the error I'm seeing and open a new issue. It will take about a week for me to do this as I'm tackling another issue at the moment.

**Comment by gtb104** [comment] 2020-01-14 19:15
My bad. It was an error in one of the other uses of ember-sortable on the page that was causing the issue. All seems well!

**Comment by joshuaswift** [comment] 2020-03-30 08:50
Hey! I just opened a new issue very similar to this (#363) - @gtb104 if possible could you share how you resolved your `this.registerItem is not a function` error?

**Comment by gtb104** [comment] 2020-04-28 13:22
My apologies, just saw this. I don't remember what I did to solve this. I guess I should have put that info here so I don't need to rely upon me remembering.
